# Generated by Django 2.1.11 on 2019-10-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_maintenance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
