# Generated by Django 2.1.11 on 2019-10-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_maintenance_app', '0002_car_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='nickname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
