# Generated by Django 2.1.11 on 2019-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_maintenance_app', '0003_car_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='service',
            field=models.CharField(max_length=20),
        ),
    ]
